// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deletedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedata));
        
        string IMigrationMetadata.Id
        {
            get { return "202311031418295_deletedata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
